import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val appcompat: String = "androidx.appcompat:appcompat:_"

    const val core_testing: String = "androidx.arch.core:core-testing:_"

    const val camera_camera2: String = "androidx.camera:camera-camera2:_"

    const val androidx_compose_compiler_compiler: String = "androidx.compose.compiler:compiler:_"

    const val foundation: String = "androidx.compose.foundation:foundation:_"

    const val androidx_compose_material_material: String = "androidx.compose.material:material:_"

    const val material_icons_core: String = "androidx.compose.material:material-icons-core:_"

    const val material_icons_extended: String =
            "androidx.compose.material:material-icons-extended:_"

    const val navigation_compose: String = "androidx.navigation:navigation-compose:_"

    const val activity_compose: String = "androidx.activity:activity-compose:_"

    const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    const val converter_gson: String = "com.squareup.retrofit2:converter-gson:_"

    const val okhttp: String = "com.squareup.okhttp3:okhttp:_"

    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:_"

    const val gson: String = "com.google.code.gson:gson:_"

    const val lifecycle_viewmodel_compose = "androidx.lifecycle:lifecycle-viewmodel-compose:_"

    const val hilt_navigation_compose: String = "androidx.hilt:hilt-navigation-compose:_"

    const val runtime_livedata: String = "androidx.compose.runtime:runtime-livedata:_"

    const val ui: String = "androidx.compose.ui:ui:_"

    const val ui_test_junit4: String = "androidx.compose.ui:ui-test-junit4:_"

    const val ui_tooling: String = "androidx.compose.ui:ui-tooling:_"

    const val viewbinding: String = "androidx.databinding:viewbinding:_"

    const val espresso_contrib: String = "androidx.test.espresso:espresso-contrib:_"

    const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    const val espresso_idling_resource: String = "androidx.test.espresso:espresso-idling-resource:_"

    const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    const val androidx_test_rules: String = "androidx.test:rules:_"

    const val androidx_test_runner: String = "androidx.test:runner:_"

    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:_"

    const val com_google_android_material_material: String =
            "com.google.android.material:material:_"

    const val hilt_android_gradle_plugin: String = "com.google.dagger:hilt-android-gradle-plugin:_"

    const val hilt_android: String = "com.google.dagger:hilt-android:_"

    const val hilt_android_compiler: String = "com.google.dagger:hilt-android-compiler:_"

    const val google_services: String = "com.google.gms:google-services:_"

    const val truth: String = "com.google.truth:truth:_"

    const val timber: String = "com.jakewharton.timber:timber:_"

    const val ktlint: String = "com.pinterest:ktlint:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:_"

    const val junit_junit: String = "junit:junit:_"

    const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String =
            "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin:_"

    const val mockito_core: String = "org.mockito:mockito-core:_"
}
